import 'package:fpdart/fpdart.dart';
import 'package:project_pipeline/core/error/failure.dart';
import 'package:project_pipeline/core/usecase/usecase.dart';
import 'package:project_pipeline/features/projects/domain/entities/sprint_entity.dart';
import 'package:project_pipeline/features/projects/domain/repositories/sprint_repository.dart';

class CreateSprint implements UseCase<String, CreateSprintParams> {
  final SprintRepository repository;

  CreateSprint(this.repository);

  @override
  Future<Either<Failure, String>> call(CreateSprintParams params) async {
    final sprint = SprintEntity(
      id: '', // Will be generated by Firestore
      projectId: params.projectId,
      name: params.name,
      goal: params.goal,
      startDate: params.startDate,
      endDate: params.endDate,
      status: SprintStatus.planning,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      createdBy: params.createdBy,
    );

    return await repository.createSprint(sprint);
  }
}

class CreateSprintParams {
  final String projectId;
  final String name;
  final String? goal;
  final DateTime startDate;
  final DateTime endDate;
  final String createdBy;

  CreateSprintParams({
    required this.projectId,
    required this.name,
    this.goal,
    required this.startDate,
    required this.endDate,
    required this.createdBy,
  });
}

